ARG JDK_VERSION
ARG WILDFLY_VERSION
FROM rdohna/wildfly:${WILDFLY_VERSION}-jdk${JDK_VERSION}
# we need to redefine ARG WILDFLY_VERSION, so it's still available after the FROM
ARG WILDFLY_VERSION
ARG GRAPHQL_FEATURE_PACK_VERSION

USER root
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends unzip

USER wildfly
COPY install-overlay.sh $JBOSS_HOME/install-overlay.sh
RUN ./install-overlay.sh $WILDFLY_VERSION $GRAPHQL_FEATURE_PACK_VERSION && \
    rm install-overlay.sh

COPY setup-graphql.cli $JBOSS_HOME/setup-graphql.cli
RUN $JBOSS_HOME/bin/jboss-cli.sh --file=setup-graphql.cli && \
    rm -r setup-graphql.cli standalone/configuration/standalone_xml_history
