ARG BASE_VERSION
FROM rdohna/wildfly:${BASE_VERSION}
ARG GRAPHQL_FEATURE_PACK_URL

USER root
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends unzip

USER wildfly
RUN curl -L ${GRAPHQL_FEATURE_PACK_URL} -o overlay.zip && \
    unzip overlay.zip && \
    rm overlay.zip

COPY setup-graphql.cli $JBOSS_HOME/setup-graphql.cli
RUN $JBOSS_HOME/bin/jboss-cli.sh --file=setup-graphql.cli && \
    rm -r setup-graphql.cli standalone/configuration/standalone_xml_history
