name: Build and push Docker image

on:
  push:
    branches: [ master ]
env:
  WILDFLY_25: 25.0.1.Final
  WILDFLY_26: 26.0.1.Final
  # these are used for the `latest` tag, i.e. the supposedly most stable combination
  LATEST_WILDFLY: ${{WILDFLY_26}}
  LATEST_JDK: 11

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [8, 11, 17]
        wf:
        - ${{WILDFLY_25}}
        - ${{WILDFLY_26}}
    name: ${{matrix.wf}}-${{matrix.jdk}}
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u rdohna --password-stdin
    - name: set LATEST_TAG
      run: echo "LATEST_TAG=--tag rdohna/wildfly:latest" >> $GITHUB_ENV
      if: ${{matrix.wf == env.LATEST_WILDFLY && matrix.jdk == env.LATEST_JDK}}
    - name: build and push the base image
      run: >
        docker buildx build . --push --platform linux/arm64,linux/amd64
        --tag rdohna/wildfly:${{matrix.wf}}-jdk${{matrix.jdk}}
        --build-arg JDK_VERSION=${{matrix.jdk}}
        --build-arg WILDFLY_VERSION=${{matrix.wf}}

    - name: set graphql feature pack version 25
      run: echo "GRAPHQL_FEATURE_PACK_VERSION=1.4.2.Final" >> $GITHUB_ENV
      if: ${{matrix.wf == env.WILDFLY_25}}
    - name: set graphql feature pack version 26
      run: echo "GRAPHQL_FEATURE_PACK_VERSION=1.6.0.Final" >> $GITHUB_ENV
      if: ${{matrix.wf == env.WILDFLY_26}}

    - name: build and push the graphql image
      run: >
        docker buildx build . --push --platform linux/arm64,linux/amd64
        --tag rdohna/wildfly:${{matrix.wf}}-jdk${{matrix.jdk}}-graphql
        ${{env.LATEST_TAG}}
        --build-arg JDK_VERSION=${{matrix.jdk}}
        --build-arg WILDFLY_VERSION=${{matrix.wf}}
        --build-arg GRAPHQL_FEATURE_PACK_VERSION=${{env.GRAPHQL_FEATURE_PACK_VERSION}}
        --file Dockerfile-graphql
