name: Build and push Docker image

on:
  push:
    branches: [ master ]
env:
  POSTGRESQL: 42.7.4
  # these are used for the `latest` tag, i.e. the supposedly most stable combination
  LATEST_WILDFLY: 36.0.1.Final
  LATEST_JDK: 21

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [ 17, 21 ]
        wf: # only one major/minor version! see get-wf-tag
        - 34.0.1.Final
        - 35.0.1.Final
        - 36.0.1.Final
    name: "${{matrix.wf}}-${{matrix.jdk}}"
    steps:
    - uses: actions/checkout@v5
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        username: rdohna
        password: ${{secrets.DOCKER_TOKEN}}
    - name: set LATEST_TAG
      run: echo "LATEST_TAG=--tag rdohna/wildfly:latest" >> $GITHUB_ENV
      if: ${{matrix.wf == env.LATEST_WILDFLY && matrix.jdk == env.LATEST_JDK}}
    - id: get-wf-tag-major-minor
      uses: actions/github-script@v7.0.1
      with:
        script: |
          const split = "${{matrix.wf}}".split('.');
          return `${split[0]}.${split[1]}`
        result-encoding: string
    - name: set wf major minor version env
      run: echo "MAJOR_MINOR_WF_VERSION=${{steps.get-wf-tag-major-minor.outputs.result}}" >> $GITHUB_ENV
    - id: get-wf-tag-major
      uses: actions/github-script@v7.0.1
      with:
        script: |
          const split = "${{matrix.wf}}".split('.');
          return `${split[0]}`
        result-encoding: string
    - name: set wf major minor version env
      run: echo "MAJOR_WF_VERSION=${{steps.get-wf-tag-major.outputs.result}}" >> $GITHUB_ENV

    - name: build and push the base image
      run: >
        docker buildx build . --push --platform linux/arm64,linux/amd64
        --tag rdohna/wildfly:${{env.MAJOR_MINOR_WF_VERSION}}-jdk${{matrix.jdk}}
        --tag rdohna/wildfly:${{matrix.wf}}-jdk${{matrix.jdk}}
        --build-arg JDK_VERSION=${{matrix.jdk}}
        --build-arg WILDFLY_VERSION=${{matrix.wf}}
        --build-arg POSTGRESQL_VERSION=${{env.POSTGRESQL}}


    - name: set GraphQL Feature Pack Version (34)
      if: ${{env.MAJOR_WF_VERSION == '34'}}
      run:
        echo -e "GRAPHQL_FEATURE_PACK_VERSION=2.5.0.Final\nGRAPHQL_FEATURE_PACK_WILDFLY_VERSION=33.0.0.Final" >> $GITHUB_ENV
    - name: set GraphQL Feature Pack Version (35)
      if: ${{env.MAJOR_WF_VERSION == '35'}}
      run:
        echo -e "GRAPHQL_FEATURE_PACK_VERSION=2.5.0.Final\nGRAPHQL_FEATURE_PACK_WILDFLY_VERSION=33.0.0.Final" >> $GITHUB_ENV
    - name: set GraphQL Feature Pack Version (36)
      if: ${{env.MAJOR_WF_VERSION == '36'}}
      run:
        echo -e "GRAPHQL_FEATURE_PACK_VERSION=2.5.0.Final\nGRAPHQL_FEATURE_PACK_WILDFLY_VERSION=33.0.0.Final" >> $GITHUB_ENV
    - name: Check GRAPHQL_FEATURE_PACK_VERSION
      if: ${{env.GRAPHQL_FEATURE_PACK_VERSION == ''}}
      run:
        echo "GRAPHQL_FEATURE_PACK_VERSION not mapped"
        exit -1
    - name: set GraphQL Feature Pack Wildfly Version
      run:
        echo "GRAPHQL_FEATURE_PACK_WILDFLY_VERSION=${{env.MAJOR_WF_VERSION}}.0.0.Final" >> $GITHUB_ENV
      if: ${{env.GRAPHQL_FEATURE_PACK_WILDFLY_VERSION == ''}}

    - name: build and push the graphql image
      run: >
        docker buildx build . --push --platform linux/arm64,linux/amd64
        --tag rdohna/wildfly:${{env.MAJOR_MINOR_WF_VERSION}}-jdk${{matrix.jdk}}-graphql
        --tag rdohna/wildfly:${{matrix.wf}}-jdk${{matrix.jdk}}-graphql
        ${{env.LATEST_TAG}}
        --build-arg BASE_VERSION=${{env.MAJOR_MINOR_WF_VERSION}}-jdk${{matrix.jdk}}
        --build-arg GRAPHQL_FEATURE_PACK_VERSION=${{env.GRAPHQL_FEATURE_PACK_VERSION}}
        --build-arg GRAPHQL_FEATURE_PACK_WILDFLY_VERSION=${{env.GRAPHQL_FEATURE_PACK_WILDFLY_VERSION}}
        --file Dockerfile-graphql
