name: Build and push Docker image

on:
  push:
    branches: [ master ]
env:
  POSTGRESQL: 42.3.4
  # these are used for the `latest` tag, i.e. the supposedly most stable combination
  LATEST_WILDFLY: 27.0.1.Final
  LATEST_JDK: 17

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [ 11, 17 ]
        wf: # only one major/minor version! see get-wf-tag
        - 26.0.1.Final
        - 26.1.3.Final
        - 27.0.1.Final
        - 28.0.1.Final
    name: ${{matrix.wf}}-${{matrix.jdk}}
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        username: rdohna
        password: ${{secrets.DOCKER_TOKEN}}
    - name: set LATEST_TAG
      run: echo "LATEST_TAG=--tag rdohna/wildfly:latest" >> $GITHUB_ENV
      if: ${{matrix.wf == env.LATEST_WILDFLY && matrix.jdk == env.LATEST_JDK}}
    - id: get-wf-tag-major-minor
      uses: actions/github-script@v6.4.1
      with:
        script: |
          const split = "${{matrix.wf}}".split('.');
          return `${split[0]}.${split[1]}`
        result-encoding: string
    - name: set wf major minor version env
      run: echo "MAJOR_MINOR_WF_VERSION=${{steps.get-wf-tag-major-minor.outputs.result}}" >> $GITHUB_ENV

    - name: build and push the base image
      run: >
        docker buildx build . --push --platform linux/arm64,linux/amd64
        --tag rdohna/wildfly:${{env.MAJOR_MINOR_WF_VERSION}}-jdk${{matrix.jdk}}
        --tag rdohna/wildfly:${{matrix.wf}}-jdk${{matrix.jdk}}
        --build-arg JDK_VERSION=${{matrix.jdk}}
        --build-arg WILDFLY_VERSION=${{matrix.wf}}
        --build-arg POSTGRESQL_VERSION=${{env.POSTGRESQL}}


    - name: set GraphQL Feature Pack URL
      run:
        case "${{MAJOR_MINOR_WF_VERSION}}" in
        26.0|26.1)
          PATH=1.8.0.Final/wildfly-26.0.0.Final-mp-graphql-1.8.0.Final-overlay.zip
          ;;
        27.0)
          PATH=2.0.0.Final/wildfly-27.0.0.Final-mp-graphql-2.0.0.Final-overlay.zip
          ;;
        28.0)
          PATH=2.1.0.Final/wildfly-28.0.0.Final-mp-graphql-2.1.0.Final-SNAPSHOT-overlay.zip
          ;;
        echo "GRAPHQL_FEATURE_PACK_URL=https://github.com/wildfly-extras/wildfly-graphql-feature-pack/releases/download/${PATH}" >> $GITHUB_ENV

    - name: build and push the graphql image
      run: >
        docker buildx build . --push --platform linux/arm64,linux/amd64
        --tag rdohna/wildfly:${{env.MAJOR_MINOR_WF_VERSION}}-jdk${{matrix.jdk}}-graphql
        --tag rdohna/wildfly:${{matrix.wf}}-jdk${{matrix.jdk}}-graphql
        ${{env.LATEST_TAG}}
        --build-arg BASE_VERSION=${{env.MAJOR_MINOR_WF_VERSION}}-jdk${{matrix.jdk}}
        --build-arg GRAPHQL_FEATURE_PACK_VERSION=${{env.GRAPHQL_FEATURE_PACK_VERSION}}
        --build-arg GRAPHQL_FEATURE_PACK_WILDFLY_VERSION=${{env.MAJOR_WF_VERSION}}.0.0
        --file Dockerfile-graphql
