name: Build and push Docker image

on:
  push:
    branches: [ master ]
env:
  # these are used for the latest tag
  LATEST_JDK: 11
  LATEST_WF: 25.0.1.Final

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]
        wf:
        - 26.0.0.Final
        - 25.0.1.Final
        - 24.0.1.Final
    name: build with jdk ${{matrix.java}}
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u rdohna --password-stdin
    - name: build and push the images
      run: docker buildx build --push --platform linux/arm64,linux/amd64 --tag rdohna/wildfly:${{matrix.wf}}-jdk-${{matrix.java}} --build-arg JDK_VERSION=${{matrix.java}} --build-arg WILDFLY_VERSION=${{matrix.wf}} .

  tag-latest:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u rdohna --password-stdin
    - name: pull
      run: docker pull --platform ${{matrix.platform}} rdohna/wildfly:jdk-${{LATEST_JDK}}
    - name: tag
      run: docker tag rdohna/wildfly:${{LATEST_WF}}-jdk-${{LATEST_JDK}} rdohna/wildfly
    - name: push tag
      run: docker push rdohna/wildfly:latest
