name: Build and push Docker image

on:
  push:
    branches: [ master ]
env:
  # this is used for the `latest` tag, i.e. the supposedly most stable combination
  LATEST_TAG: 25.0.1.Final-jdk11

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [8, 11]
        wf:
#        - 26.0.0.Final
        - 25.0.1.Final
#        - 24.0.1.Final
    name: build ${{matrix.wf}} with jdk ${{matrix.jdk}}
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u rdohna --password-stdin
    - name: build and push the images
      run: docker buildx build --push --platform linux/arm64,linux/amd64 --tag rdohna/wildfly:${{matrix.wf}}-jdk${{matrix.jdk}} --build-arg JDK_VERSION=${{matrix.jdk}} .

  tag-latest:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [arm64]
    steps:
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u rdohna --password-stdin
    - name: pull
      run: docker pull --platform ${{matrix.platform}} rdohna/wildfly:${{env.LATEST_TAG}}
    - name: tag
      run: docker tag rdohna/wildfly:${{env.LATEST_TAG}} rdohna/wildfly
    - name: push tag
      run: docker push rdohna/wildfly:latest
