name: Build and push Docker image

on:
  push:
    branches: [ master ]
env:
  # these are used for the `latest` tag, i.e. the supposedly most stable combination
  LATEST_WILDFLY: 26.0.1.Final
  LATEST_JDK: jdk11

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [8, 11, 17]
        wf:
        - 26.0.1.Final
        - 25.0.1.Final
    name: ${{matrix.wf}}-${{matrix.jdk}}
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u rdohna --password-stdin
    - name: echo tags
      run: >
        echo "${{matrix.wf}} == {{env.LATEST_WILDFLY}} = ${{matrix.wf == env.LATEST_WILDFLY}} &&
        ${{matrix.jdk}} == ${{env.LATEST_JDK}} = ${{matrix.jdk == env.LATEST_JDK}}
    - name: set FINAL_TAG
      run: echo "FINAL_TAG=--tag rdohna/wildfly:latest" >> $GITHUB_ENV
      if: ${{matrix.wf == env.LATEST_WILDFLY && matrix.jdk == env.LATEST_JDK}}
    - name: echo FINAL_TAG
      run: echo ${{env.FINAL_TAG}}
    - name: build and push the images
      run: >
        docker buildx build --push --platform linux/arm64,linux/amd64
        --tag rdohna/wildfly:${{matrix.wf}}-jdk${{matrix.jdk}}
        ${{env.FINAL_TAG}}
        --build-arg JDK_VERSION=${{matrix.jdk}}
        --build-arg WILDFLY_VERSION=${{matrix.wf}}
        .
