name: Build and push Docker image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]
    name: build with jdk ${{matrix.java}}
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u rdohna --password-stdin
    - name: build and push the images
      run: docker buildx build --push --platform linux/arm64,linux/amd64 --tag rdohna/wildfly:jdk-${{matrix.java}} --build-arg JDK_VERSION=${{matrix.java}} .

  tag-latest:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u rdohna --password-stdin
    - name: pull
      run: docker pull --platform ${{matrix.platform}} rdohna/wildfly:jdk-11
    - name: tag
      run: docker tag rdohna/wildfly:jdk-11 rdohna/wildfly
    - name: push tag
      run: docker push rdohna/wildfly:latest
